version: '3'
services:
  nginx:
    container_name: nginx
    image: dev/nginx:1.14-alpine
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT:-8080}:80
      - ${SSL_PORT:-443}:443
    volumes:
      - ./:/var/www/html
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - dev_net
    links:
      - app
    depends_on:
      - mysql
      - redis
  app:
    container_name: app
    image: dev/php:8.1-fpm-alpine
    build:
      context: ./build/php
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=host.docker.internal}
    ports:
      - ${FORWARD_APP_PORT:-9000}:9000
    volumes:
      - .:/var/www/html
      - ./build/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./build/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - dev_net
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - dev_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    volumes:
      - data-redis:/data
    networks:
      - dev_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  # selenium:
  #     image: selenium/standalone-chrome
  #     volumes:
  #         - /dev/shm:/dev/shm
  #     networks:
  #         - dev_net
networks:
  dev_net:
    driver: bridge
volumes:
  data-mysql:
    driver: local
  data-redis:
    driver: local
